# -*- coding: utf-8 -*-
"""population_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kjdSyaXGiOsl5pybcu80RW1F3lbITZTw
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("population_data.csv")
df.head()

print(df.info())
df.describe()

df.isnull().sum()

df["Population 2026"] = (
    df["Population 2026"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .astype(int)
)

top_population = df.sort_values(by="Population 2026", ascending=False)

top_population.head(10)

top_population = df.sort_values(by="Population 2026",ascending=False)
top_population.head()

top10 = df.head(10)
plt.figure(figsize=(10,6))
sns.barplot(x="Country (or dependency)",y="Population 2026",data=top10)
plt.xticks(rotation=45)
plt.title("Top 10 most populated countries")
plt.show()

df["Density (P/Km²)"] = (
    df["Density (P/Km²)"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

df["Density (P/Km²)"] = pd.to_numeric(
    df["Density (P/Km²)"],
    errors="coerce"
)

high_density = df[df["Density (P/Km²)"] > 1000]

high_density

numeric_df = df.select_dtypes(include=['number'])

numeric_df.corr()

plt.figure(figsize=(8,6))

sns.heatmap(numeric_df.corr(), annot=True)

plt.title("Correlation Heatmap")

plt.show()

plt.figure(figsize=(8,6))

sns.scatterplot(
    x="Land Area (Km²)",
    y="Population 2026",
    data=df
)

plt.title("Land Area vs Population")

plt.show()