# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RvcmbqHxQ4mIkDGOn0nWN5LIMMePL5gK
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
from google.colab import files

url = "https://www.worldometers.info/world-population/population-by-country/"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.content, "html.parser")

table = soup.find("table")

headers_list = []

headers_data = table.find_all("th")

for header in headers_data:
    headers_list.append(header.text.strip())

rows = []

for row in table.find_all("tr")[1:]:
  cols = row.find_all("td")
  cols = [col.text.strip() for col in cols]

  if cols:
    rows.append(cols)

df = pd.DataFrame(rows, columns=headers_list)

df.to_csv("population_data.csv", index=False)

print(df.head())

files.download("population_data.csv")